name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - '*.x'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm run test -- --coverage
      - uses: codecov/codecov-action@v3
      - run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
